<?php $config = array(
         'signup'=>array(
		             array(
					        'field'=>'username',
							'label'=>'Username',
							'rules'=>'required|min_length[6]|max_length[12]|is_unique[user.username]'
					      ),
				     array(
					        'field'=>'password',
							'label'=>'Password',
							'rules'=>'required|min_length[6]|max_length[12]'
					      ),		  
				     array(
					        'field'=>'passconf',
							'label'=>'PasswordConfirmation',
							'rules'=>'required|matches[password]'
					      )
		              ),
		'next_signup'=>array
                      (
					     array(
					        'field'=>'realname',
							'label'=>'姓名',
							'rules'=>'required'
					      ),
                         array(
					         'field'=>'email',
							 'label'=>'Email',
							 'rules'=>'required|valid_email'
					       ) 						  
					  ),
        'change_password'=>array
                      (
					     array(
					        'field'=>'OldPassword',
							'label'=>'OldPassword',
							'rules'=>'required|min_length[6]|max_length[12]'
					       ),
                         array(
					         'field'=>'NewPassword',
							'label'=>'NewPassword',
							'rules'=>'required|min_length[6]|max_length[12]'
					        ),
                         array(
					         'field'=>'Passconf',
							'label'=>'Passconf',
							'rules'=>'required|matches[NewPassword]'
					       )						   
					  )							  
					  
               );			   
?>